{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "#import dask.dataframe as ddf\n",
    "import dask.distributed as dds\n",
    "from dask import bag as db\n",
    "import time\n",
    "import random\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<table style=\"border: 2px solid white;\">\n",
       "<tr>\n",
       "<td style=\"vertical-align: top; border: 0px solid white\">\n",
       "<h3>Client</h3>\n",
       "<ul>\n",
       "  <li><b>Scheduler: </b>tcp://127.0.0.1:54169\n",
       "  <li><b>Dashboard: </b><a href='http://127.0.0.1:54170' target='_blank'>http://127.0.0.1:54170</a>\n",
       "</ul>\n",
       "</td>\n",
       "<td style=\"vertical-align: top; border: 0px solid white\">\n",
       "<h3>Cluster</h3>\n",
       "<ul>\n",
       "  <li><b>Workers: </b>4</li>\n",
       "  <li><b>Cores: </b>4</li>\n",
       "  <li><b>Memory: </b>8.49 GB</li>\n",
       "</ul>\n",
       "</td>\n",
       "</tr>\n",
       "</table>"
      ],
      "text/plain": [
       "<Client: scheduler='tcp://127.0.0.1:54169' processes=4 cores=4>"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "cluster = dds.LocalCluster()\n",
    "client = dds.Client(cluster)\n",
    "client"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "cluster.close()\n",
    "client.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 59,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "data = list(np.random.randint(0,100,size=(1000)))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 60,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "def funct(x):\n",
    "    time.sleep(0.01)\n",
    "    return x*2"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Sequential processing"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 61,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Wall time: 16.7 s\n"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "res_seq=[]\n",
    "for item, i in zip (data, range(len(data))):\n",
    "    res_seq.append(funct(item))\n",
    "    print('%d/%d'%(i,len(data)),end='\\r')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Distributed Parallel processing"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 62,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "bag = db.from_sequence(data)\n",
    "res_distr_graph = bag.map(funct)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 63,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Wall time: 4.62 s\n"
     ]
    }
   ],
   "source": [
    "%%time \n",
    "res_distr = res_distr_graph.compute()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 79,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "res_filter = bag.filter(predicate=lambda x: funct(x)%3==2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 81,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Wall time: 4.62 s\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "[16,\n",
       " 88,\n",
       " 85,\n",
       " 1,\n",
       " 1,\n",
       " 1,\n",
       " 43,\n",
       " 55,\n",
       " 82,\n",
       " 97,\n",
       " 1,\n",
       " 46,\n",
       " 76,\n",
       " 76,\n",
       " 94,\n",
       " 43,\n",
       " 55,\n",
       " 58,\n",
       " 37,\n",
       " 1,\n",
       " 58,\n",
       " 34,\n",
       " 58,\n",
       " 49,\n",
       " 28,\n",
       " 1,\n",
       " 52,\n",
       " 19,\n",
       " 64,\n",
       " 34,\n",
       " 70,\n",
       " 28,\n",
       " 49,\n",
       " 43,\n",
       " 73,\n",
       " 76,\n",
       " 79,\n",
       " 22,\n",
       " 43,\n",
       " 28,\n",
       " 1,\n",
       " 64,\n",
       " 13,\n",
       " 79,\n",
       " 88,\n",
       " 16,\n",
       " 40,\n",
       " 88,\n",
       " 82,\n",
       " 97,\n",
       " 52,\n",
       " 22,\n",
       " 94,\n",
       " 85,\n",
       " 73,\n",
       " 64,\n",
       " 4,\n",
       " 4,\n",
       " 52,\n",
       " 43,\n",
       " 76,\n",
       " 22,\n",
       " 64,\n",
       " 10,\n",
       " 58,\n",
       " 34,\n",
       " 58,\n",
       " 40,\n",
       " 28,\n",
       " 28,\n",
       " 76,\n",
       " 25,\n",
       " 49,\n",
       " 58,\n",
       " 97,\n",
       " 58,\n",
       " 79,\n",
       " 58,\n",
       " 91,\n",
       " 13,\n",
       " 67,\n",
       " 61,\n",
       " 13,\n",
       " 73,\n",
       " 7,\n",
       " 85,\n",
       " 16,\n",
       " 34,\n",
       " 79,\n",
       " 73,\n",
       " 64,\n",
       " 64,\n",
       " 58,\n",
       " 22,\n",
       " 79,\n",
       " 76,\n",
       " 13,\n",
       " 85,\n",
       " 43,\n",
       " 94,\n",
       " 70,\n",
       " 64,\n",
       " 58,\n",
       " 34,\n",
       " 52,\n",
       " 4,\n",
       " 97,\n",
       " 46,\n",
       " 97,\n",
       " 43,\n",
       " 34,\n",
       " 25,\n",
       " 73,\n",
       " 49,\n",
       " 55,\n",
       " 10,\n",
       " 91,\n",
       " 82,\n",
       " 88,\n",
       " 85,\n",
       " 55,\n",
       " 1,\n",
       " 13,\n",
       " 37,\n",
       " 61,\n",
       " 43,\n",
       " 28,\n",
       " 34,\n",
       " 19,\n",
       " 58,\n",
       " 49,\n",
       " 22,\n",
       " 4,\n",
       " 67,\n",
       " 73,\n",
       " 13,\n",
       " 49,\n",
       " 37,\n",
       " 88,\n",
       " 91,\n",
       " 97,\n",
       " 34,\n",
       " 91,\n",
       " 13,\n",
       " 43,\n",
       " 28,\n",
       " 34,\n",
       " 25,\n",
       " 31,\n",
       " 31,\n",
       " 28,\n",
       " 52,\n",
       " 1,\n",
       " 34,\n",
       " 76,\n",
       " 13,\n",
       " 79,\n",
       " 58,\n",
       " 16,\n",
       " 88,\n",
       " 4,\n",
       " 7,\n",
       " 61,\n",
       " 22,\n",
       " 49,\n",
       " 97,\n",
       " 55,\n",
       " 19,\n",
       " 46,\n",
       " 85,\n",
       " 58,\n",
       " 55,\n",
       " 67,\n",
       " 40,\n",
       " 64,\n",
       " 85,\n",
       " 7,\n",
       " 37,\n",
       " 25,\n",
       " 31,\n",
       " 25,\n",
       " 4,\n",
       " 55,\n",
       " 70,\n",
       " 10,\n",
       " 49,\n",
       " 31,\n",
       " 40,\n",
       " 49,\n",
       " 82,\n",
       " 40,\n",
       " 40,\n",
       " 85,\n",
       " 82,\n",
       " 79,\n",
       " 34,\n",
       " 37,\n",
       " 73,\n",
       " 37,\n",
       " 28,\n",
       " 58,\n",
       " 22,\n",
       " 10,\n",
       " 94,\n",
       " 55,\n",
       " 46,\n",
       " 79,\n",
       " 19,\n",
       " 1,\n",
       " 46,\n",
       " 73,\n",
       " 97,\n",
       " 49,\n",
       " 13,\n",
       " 79,\n",
       " 7,\n",
       " 19,\n",
       " 46,\n",
       " 55,\n",
       " 61,\n",
       " 61,\n",
       " 61,\n",
       " 10,\n",
       " 64,\n",
       " 67,\n",
       " 70,\n",
       " 55,\n",
       " 34,\n",
       " 43,\n",
       " 31,\n",
       " 61,\n",
       " 91,\n",
       " 82,\n",
       " 88,\n",
       " 64,\n",
       " 94,\n",
       " 70,\n",
       " 43,\n",
       " 88,\n",
       " 22,\n",
       " 76,\n",
       " 85,\n",
       " 10,\n",
       " 88,\n",
       " 49,\n",
       " 28,\n",
       " 79,\n",
       " 55,\n",
       " 64,\n",
       " 91,\n",
       " 13,\n",
       " 49,\n",
       " 67,\n",
       " 34,\n",
       " 85,\n",
       " 88,\n",
       " 52,\n",
       " 88,\n",
       " 82,\n",
       " 34,\n",
       " 31,\n",
       " 7,\n",
       " 28,\n",
       " 64,\n",
       " 37,\n",
       " 55,\n",
       " 25,\n",
       " 88,\n",
       " 70,\n",
       " 55,\n",
       " 31,\n",
       " 52,\n",
       " 37,\n",
       " 25,\n",
       " 40,\n",
       " 70,\n",
       " 10,\n",
       " 49,\n",
       " 7,\n",
       " 10,\n",
       " 52,\n",
       " 4,\n",
       " 43,\n",
       " 70,\n",
       " 19,\n",
       " 46,\n",
       " 61,\n",
       " 85,\n",
       " 28,\n",
       " 13,\n",
       " 49,\n",
       " 55,\n",
       " 79,\n",
       " 37,\n",
       " 10,\n",
       " 37,\n",
       " 73,\n",
       " 64,\n",
       " 31,\n",
       " 19,\n",
       " 7,\n",
       " 28,\n",
       " 28,\n",
       " 82,\n",
       " 7,\n",
       " 67,\n",
       " 67,\n",
       " 67,\n",
       " 55,\n",
       " 52,\n",
       " 97,\n",
       " 49,\n",
       " 28,\n",
       " 79,\n",
       " 25,\n",
       " 55,\n",
       " 79]"
      ]
     },
     "execution_count": 81,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D115ECBF60> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D115ECBE10> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D115ECBCC0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D115ECBB70> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D115ECBA20> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D115ECB8D0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D115ECB780> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D115ECB630> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D115ECB4E0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D115ECB390> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D115ECB240> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D115ECB0F0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159EBF60> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159EBE10> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159EBCC0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159EBB70> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159EBA20> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159EB8D0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159EB780> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159EB630> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159EB4E0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159EB390> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159EB240> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159EB0F0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159EDF60> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159EDE10> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159EDCC0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159EDA20> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159ED8D0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159ED780> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159ED630> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159ED4E0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159ED390> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159ED240> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159ED0F0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159EFF60> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159EFE10> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159EFCC0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159EFB70> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159EFA20> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159EF8D0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159EF780> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159EF630> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159EF4E0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159EF390> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159EF240> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159EF0F0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159C4F60> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159C4E10> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159C4CC0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159C4B70> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159C4A20> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159C48D0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159C4780> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159C4630> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159C44E0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159C4390> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159C4240> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159C40F0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159B5F60> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159B5E10> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159B5CC0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159B5B70> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159B5A20> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159B58D0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159B5780> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159B5630> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159B5390> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159B5240> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159B50F0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D115997F60> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D115997E10> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D115997CC0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D115997B70> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D115997A20> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159978D0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D115997780> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D115997630> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159974E0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D115997390> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D115997240> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159970F0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D115996F60> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D115996E10> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D115996CC0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D115996B70> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D115996A20> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D115996860> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1157A66A0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159BE160> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159BE2B0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159BE400> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D1159BE550> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D115EE79B0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D115EE7DA0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x000001D115EE7EF0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\tornado\\gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"C:\\Users\\mkosturek\\Anaconda3\\lib\\site-packages\\distributed\\client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "res_filter.compute()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "client"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.3"
  },
  "toc": {
   "nav_menu": {},
   "number_sections": true,
   "sideBar": true,
   "skip_h1_title": false,
   "toc_cell": false,
   "toc_position": {},
   "toc_section_display": "block",
   "toc_window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
